Refactor apply and delete

diff --git a/apply b/apply
--- a/apply
+++ b/apply
@@ -1,43 +1,20 @@
 #!/usr/bin/env sh
 
 # check if connection to k8s API is ready
-kubectl get nodes > /dev/null 2>&1
+WKDIR=$(dirname "$(readlink -f basename "$0")")
+"$WKDIR"/util/check-oke-connection.sh
 RESULT=$?
-if [ $RESULT -eq 1 ]
+if [ $RESULT -eq 0 ]
 then
-    # get util path
-    WKDIR=$(dirname "$(readlink -f basename "$0")")
-    echo "Initiating connection to k8s cluster at $(date)..."
-    TUNNELSCRIPT="$WKDIR/util/oke-tunnel.sh"
-    if [ ! -f "$TUNNELSCRIPT" ]
-    then
-        echo '* ERROR! Missing '"$TUNNELSCRIPT"
-        exit 3
-    fi
-    nohup "$TUNNELSCRIPT" 2>&1 &
-    while true
-    do
-        kubectl get nodes > /dev/null 2>&1
-        STATUS=`echo $?`
-    	if [ $STATUS -eq 0 ]
-    	then
-    	  echo '*'" Connection is ready at $(date)"
-    	  break;
-    	else
-    	  echo '* Retrying in 5s...'
-    	  sleep 5
-    	fi
-    done
+  # execute
+  for YAML in "$@"
+  do
+      if [ -f "$YAML" ]
+      then
+          kubectl apply -f "$YAML"
+      else
+          echo "File [$YAML] not found"
+          exit 1
+      fi
+  done
 fi
-
-# execute
-for YAML in "$@"
-do
-    if [ -f "$YAML" ]
-    then
-        kubectl apply -f "$YAML"
-    else
-        echo "File [$YAML] not found"
-        exit 1
-    fi
-done
